// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqg945nlWrkJtY1gAw6ITotaWiBzn67Fo',
    appId: '1:662929013582:web:0441dd42d515a0d59cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    authDomain: 'abdulrahmanabusnena-70718.firebaseapp.com',
    storageBucket: 'abdulrahmanabusnena-70718.appspot.com',
    measurementId: 'G-S783NZCHD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmkyEHYEuKGeNcHet-QMk0fj8OvyBBcX4',
    appId: '1:662929013582:android:051045f16f242cf39cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    storageBucket: 'abdulrahmanabusnena-70718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDmiN1MxVO0YI4Dwu6GoQPivVvfwQZis',
    appId: '1:662929013582:ios:aa274f5252a764ba9cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    storageBucket: 'abdulrahmanabusnena-70718.appspot.com',
    iosBundleId: 'com.abdul.abdul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDmiN1MxVO0YI4Dwu6GoQPivVvfwQZis',
    appId: '1:662929013582:ios:876053f1f760c0c09cbc1f',
    messagingSenderId: '662929013582',
    projectId: 'abdulrahmanabusnena-70718',
    storageBucket: 'abdulrahmanabusnena-70718.appspot.com',
    iosBundleId: 'com.abdul.abdul.RunnerTests',
  );
}
